In [1]:
import calc,pokemon,move,field
from field import Side

## To Do

Test the one v one damage method

## Ditto Testing

In [2]:
ditto = pokemon.Pokemon(
    name="Ditto",
    level=100,
    gen=9,
    item="Choice Scarf",
    nature="Bold",
    evs={"hp" : 252, "spd" : 252}
    )

In [3]:
chansey = pokemon.Pokemon(
    name="Chansey",
    item="Eviolite",
    nature="Bold",
    ability="Natural Cure",
    evs={"hp" : 252, "def" : 252},
    gen=9)

In [4]:
flip = move.Move(name="Flip Turn", gen=9)

In [5]:
curr_field = field.Field(weather="Snow",terrain="Electric",defenderSide=Side(isReflect=True))

In [6]:
calc.calculate(gen=9,attacker=ditto,defender=chansey,move=flip,field=curr_field)

{'gen': 9,
 'attacker': {'name': 'Ditto',
  'ability': 'Limber',
  'item': 'Choice Scarf',
  'level': 100,
  'nature': 'Bold',
  'types': ['Normal'],
  'stats': {'hp': 300,
   'atk': 118,
   'def': 145,
   'spa': 132,
   'spd': 195,
   'spe': 198},
  'rawStats': {'hp': 300,
   'atk': 118,
   'def': 145,
   'spa': 132,
   'spd': 195,
   'spe': 132},
  'boosts': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 0, 'spe': 0},
  'originalCurHP': 300,
  'isDynamaxed': None,
  'teraType': None,
  'status': '',
  'toxicCounter': 0},
 'defender': {'name': 'Chansey',
  'ability': 'Natural Cure',
  'item': 'Eviolite',
  'level': 100,
  'nature': 'Bold',
  'types': ['Normal'],
  'stats': {'hp': 704,
   'atk': 41,
   'def': 119,
   'spa': 106,
   'spd': 246,
   'spe': 136},
  'rawStats': {'hp': 704,
   'atk': 41,
   'def': 119,
   'spa': 106,
   'spd': 246,
   'spe': 136},
  'boosts': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 0, 'spe': 0},
  'originalCurHP': 704,
  'isDynamaxed': None,
  'teraTy

In [7]:
calc.calculate(gen=9,attacker=chansey,defender=chansey,move=flip,field=curr_field)

{'gen': 9,
 'attacker': {'name': 'Chansey',
  'ability': 'Natural Cure',
  'item': 'Eviolite',
  'level': 100,
  'nature': 'Bold',
  'types': ['Normal'],
  'stats': {'hp': 704,
   'atk': 41,
   'def': 119,
   'spa': 106,
   'spd': 246,
   'spe': 136},
  'rawStats': {'hp': 704,
   'atk': 41,
   'def': 119,
   'spa': 106,
   'spd': 246,
   'spe': 136},
  'boosts': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 0, 'spe': 0},
  'originalCurHP': 704,
  'isDynamaxed': None,
  'teraType': None,
  'status': '',
  'toxicCounter': 0},
 'defender': {'name': 'Chansey',
  'ability': 'Natural Cure',
  'item': 'Eviolite',
  'level': 100,
  'nature': 'Bold',
  'types': ['Normal'],
  'stats': {'hp': 704,
   'atk': 41,
   'def': 119,
   'spa': 106,
   'spd': 246,
   'spe': 136},
  'rawStats': {'hp': 704,
   'atk': 41,
   'def': 119,
   'spa': 106,
   'spd': 246,
   'spe': 136},
  'boosts': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 0, 'spe': 0},
  'originalCurHP': 704,
  'isDynamaxed': None,
  'tera

In [8]:
new_ditto,chansey = calc.ditto_transform(ditto,chansey)
calc.calculate(gen=9,attacker=new_ditto,defender=chansey,move=flip,field=curr_field)

{'gen': 9,
 'attacker': {'name': 'Chansey',
  'ability': 'Natural Cure',
  'item': 'Choice Scarf',
  'level': 100,
  'nature': 'Bold',
  'types': ['Normal'],
  'stats': {'hp': 300,
   'atk': 41,
   'def': 119,
   'spa': 106,
   'spd': 246,
   'spe': 204},
  'rawStats': {'hp': 300,
   'atk': 41,
   'def': 119,
   'spa': 106,
   'spd': 246,
   'spe': 136},
  'boosts': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 0, 'spe': 0},
  'originalCurHP': 300,
  'isDynamaxed': None,
  'teraType': None,
  'status': '',
  'toxicCounter': 0},
 'defender': {'name': 'Chansey',
  'ability': 'Natural Cure',
  'item': 'Eviolite',
  'level': 100,
  'nature': 'Bold',
  'types': ['Normal'],
  'stats': {'hp': 704,
   'atk': 41,
   'def': 119,
   'spa': 106,
   'spd': 246,
   'spe': 136},
  'rawStats': {'hp': 704,
   'atk': 41,
   'def': 119,
   'spa': 106,
   'spd': 246,
   'spe': 136},
  'boosts': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 0, 'spe': 0},
  'originalCurHP': 704,
  'isDynamaxed': None,
  '

In [9]:
chansey,new_ditto = calc.ditto_transform(chansey,ditto)
calc.calculate(gen=9,attacker=chansey,defender=new_ditto,move=flip,field=curr_field)

{'gen': 9,
 'attacker': {'name': 'Chansey',
  'ability': 'Natural Cure',
  'item': 'Eviolite',
  'level': 100,
  'nature': 'Bold',
  'types': ['Normal'],
  'stats': {'hp': 704,
   'atk': 41,
   'def': 119,
   'spa': 106,
   'spd': 246,
   'spe': 136},
  'rawStats': {'hp': 704,
   'atk': 41,
   'def': 119,
   'spa': 106,
   'spd': 246,
   'spe': 136},
  'boosts': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 0, 'spe': 0},
  'originalCurHP': 704,
  'isDynamaxed': None,
  'teraType': None,
  'status': '',
  'toxicCounter': 0},
 'defender': {'name': 'Chansey',
  'ability': 'Natural Cure',
  'item': 'Choice Scarf',
  'level': 100,
  'nature': 'Bold',
  'types': ['Normal'],
  'stats': {'hp': 300,
   'atk': 41,
   'def': 119,
   'spa': 106,
   'spd': 246,
   'spe': 204},
  'rawStats': {'hp': 300,
   'atk': 41,
   'def': 119,
   'spa': 106,
   'spd': 246,
   'spe': 136},
  'boosts': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 0, 'spe': 0},
  'originalCurHP': 300,
  'isDynamaxed': None,
  '

## Sandbox

In [10]:
gengar = pokemon.Pokemon(
    gen=9,
    name="Gengar",
    level=100,
    item="Choice Specs",
    nature="Timid",
    evs={"spa" : 252, "spe" : 252, "spd" : 4},
    moves = ["Shadow Ball", "Sludge Wave", "Thunderbolt", "Focus Blast"],
    curHP=261)

In [11]:
palafin = pokemon.Pokemon(
    name="Palafin-Hero",
    gen=9,
    level=100,
    moves=["Bulk Up", "Flip Turn","Wave Crash","Drain Punch"],
    evs={"hp" : 248, "atk" : 8, "spd" : 252},
    nature="Careful",
    item="Leftovers")

In [12]:
test_field = field.Field(attackerSide=Side(isTailwind=True))

In [13]:
calc.calculate(gen = 9, attacker = palafin, defender = gengar, move = move.Move(gen = 9, name = "Quick Attack"),field=test_field)

{'gen': 9,
 'attacker': {'name': 'Palafin-Hero',
  'ability': 'Zero to Hero',
  'item': 'Leftovers',
  'level': 100,
  'nature': 'Careful',
  'types': ['Water'],
  'stats': {'hp': 403,
   'atk': 358,
   'def': 230,
   'spa': 223,
   'spd': 300,
   'spe': 472},
  'rawStats': {'hp': 403,
   'atk': 358,
   'def': 230,
   'spa': 223,
   'spd': 300,
   'spe': 236},
  'boosts': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 0, 'spe': 0},
  'originalCurHP': 403,
  'isDynamaxed': None,
  'teraType': None,
  'status': '',
  'toxicCounter': 0},
 'defender': {'name': 'Gengar',
  'ability': 'Cursed Body',
  'item': 'Choice Specs',
  'level': 100,
  'nature': 'Timid',
  'types': ['Ghost', 'Poison'],
  'stats': {'hp': 261,
   'atk': 149,
   'def': 156,
   'spa': 359,
   'spd': 187,
   'spe': 350},
  'rawStats': {'hp': 261,
   'atk': 149,
   'def': 156,
   'spa': 359,
   'spd': 187,
   'spe': 350},
  'boosts': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 0, 'spe': 0},
  'originalCurHP': 261,
  'isD

In [14]:
calc.one_v_one_calcs(gen=9,m1 = palafin, m2 = gengar)

([297, 403, 236, False], [232, 261, 350, False])

In [17]:
calc.advantage(m1=palafin,m2=gengar,field=field.Field(),num_hp_states=10,print_matrix=True)

[[ 0.42431762  0.42431762  0.42431762  0.42431762  0.42431762  0.42431762
   0.42431762  0.42431762  0.42431762  0.42431762]
 [ 0.35911602  0.35911602  0.35911602  0.35911602  0.35911602  0.35911602
   0.35911602  0.35911602  0.35911602  0.35911602]
 [ 0.27950311  0.27950311  0.27950311  0.27950311  0.27950311  0.27950311
   0.27950311  0.27950311  0.27950311  0.27950311]
 [ 0.17730496  0.17730496  0.17730496  0.17730496  0.17730496  0.17730496
   0.17730496  0.17730496  0.17730496  0.17730496]
 [ 0.0373444   0.0373444   0.0373444   0.0373444   0.0373444   0.0373444
   0.0373444   0.0373444   0.0373444   0.0373444 ]
 [-1.         -1.         -1.         -1.         -1.         -1.
  -1.         -1.         -1.         -1.        ]
 [-1.         -1.         -1.         -1.         -1.         -1.
  -1.         -1.         -1.         -1.        ]
 [-1.         -1.         -1.         -1.         -1.         -1.
  -1.         -1.         -1.         -1.        ]
 [-1.         -1.        

np.float64(-0.3722413891565229)

In [18]:
swampert = pokemon.Pokemon(
    name="Swampert",
    gen=9,
    level=100,
    ability="Torrent",
    item="Leftovers",
    nature="Impish",
    evs={"hp" : 252, "def" : 252, "spd" : 4},
    moves=["Earthquake","Knock Off","Flip Turn","Liquidation"])

In [20]:
corviknight = pokemon.Pokemon(
    name="Corviknight",
    gen=9,
    level=100,
    item="Rocky Helmet",
    nature="Impish",
    evs={"hp" : 248, "def" : 252, "spd" : 8},
    moves=["Brave Bird","U-turn","Roost","Body Press"]
)

In [22]:
calc.advantage(m1=swampert,m2=corviknight,num_hp_states=5,print_matrix=True)

[[-0.30827068 -0.13479624  0.10891089  0.33168317  0.55445545]
 [-0.48120301 -0.35109718 -0.13389121  0.16408669  0.44272446]
 [-0.65413534 -0.56739812 -0.42259414 -0.13207547  0.25619835]
 [-0.82706767 -0.78369906 -0.71129707 -0.56603774 -0.12658228]
 [-1.         -1.         -1.         -1.         -1.        ]]


np.float64(-0.3736834481031306)